### ISSUE TITLE
Brian's to-do list

### ISSUE THREAD

**Issue by brtarran** [finnoh/rwds_template_proposal#6]
- [x] Check on whether "citation" location can be specified, like references
- [ ] Add "content brief" to repo
- [ ] Update RWDS documentation to point to template repo

**Comment by brtarran** [comment]
It doesn't seem that it's possible to set `citation:` to a custom specified location in the same way that you can with references.
